import { Transaction } from "./columns";

export const data: Transaction[] = [
	{
		id: "m5gr84i9",
		amount: 316,
		date: new Date(),
		receipt: true,
		email: "ken99@yahoo.com",
		groupOn: "Monday, 10/06/2023",
		name: "Kenneth Johnson",
		transactionLocation: "New York City, NY",
		transactionIssuer: "Sarah Thompson",
	},
	{
		id: "3u1reuv4",
		amount: 242,
		date: new Date(),
		receipt: false,
		email: "Abe45@gmail.com",
		groupOn: "Monday, 10/06/2023",
		name: "Abraham Lincoln",
		transactionLocation: "Springfield, IL",
		transactionIssuer: "Mary Todd",
	},
	{
		id: "derv1ws0",
		amount: 837,
		date: new Date(),
		receipt: true,
		email: "Monserrat44@gmail.com",
		groupOn: "Monday, 10/06/2023",
		name: "Monserrat Rodriguez",
		transactionLocation: "Miami, FL",
		transactionIssuer: "Carlos Sanchez",
	},
	{
		id: "5kma53ae",
		amount: 874,
		date: new Date(),
		receipt: false,
		email: "Silas22@gmail.com",
		groupOn: "Pending",
		name: "Silas Green",
		transactionLocation: "Austin, TX",
		transactionIssuer: "Emma Watson",
	},
	{
		id: "bhqecj4p",
		amount: 721,
		date: new Date(),
		receipt: false,
		email: "carmella@hotmail.com",
		groupOn: "Pending",
		name: "Carmella White",
		transactionLocation: "Los Angeles, CA",
		transactionIssuer: "David Chen",
	},
	{
		id: "9k3xvs2q",
		amount: 563,
		date: new Date(),
		receipt: true,
		email: "lucas78@gmail.com",
		groupOn: "Tuesday, 10/07/2023",
		name: "Lucas Brown",
		transactionLocation: "Chicago, IL",
		transactionIssuer: "Olivia Martinez",
	},
	{
		id: "7h2ftu8l",
		amount: 429,
		date: new Date(),
		receipt: false,
		email: "emma55@yahoo.com",
		groupOn: "Tuesday, 10/07/2023",
		name: "Emma Davis",
		transactionLocation: "Seattle, WA",
		transactionIssuer: "Daniel Lee",
	},
	{
		id: "1p9xzm3r",
		amount: 692,
		date: new Date(),
		receipt: true,
		email: "noah33@hotmail.com",
		groupOn: "Tuesday, 10/07/2023",
		name: "Noah Wilson",
		transactionLocation: "Denver, CO",
		transactionIssuer: "Sophia Rodriguez",
	},
	{
		id: "4w6ybn0c",
		amount: 518,
		date: new Date(),
		receipt: false,
		email: "sophia12@gmail.com",
		groupOn: "Pending",
		name: "Sophia Taylor",
		transactionLocation: "Boston, MA",
		transactionIssuer: "Ethan Brown",
	},
	{
		id: "2t8jkl5x",
		amount: 935,
		date: new Date(),
		receipt: true,
		email: "oliver89@yahoo.com",
		groupOn: "Wednesday, 10/08/2023",
		name: "Oliver Anderson",
		transactionLocation: "San Francisco, CA",
		transactionIssuer: "Ava Johnson",
	},
	{
		id: "m5gr84i9",
		amount: 316,
		date: new Date(),
		receipt: true,
		email: "ken99@yahoo.com",
		groupOn: "Monday, 10/06/2023",
		name: "Kenneth Johnson",
		transactionLocation: "New York City, NY",
		transactionIssuer: "Sarah Thompson",
	},
	{
		id: "3u1reuv4",
		amount: 242,
		date: new Date(),
		receipt: false,
		email: "Abe45@gmail.com",
		groupOn: "Monday, 10/06/2023",
		name: "Abraham Lincoln",
		transactionLocation: "Springfield, IL",
		transactionIssuer: "Mary Todd",
	},
	{
		id: "derv1ws0",
		amount: 837,
		date: new Date(),
		receipt: true,
		email: "Monserrat44@gmail.com",
		groupOn: "Monday, 10/06/2023",
		name: "Monserrat Rodriguez",
		transactionLocation: "Miami, FL",
		transactionIssuer: "Carlos Sanchez",
	},
	{
		id: "5kma53ae",
		amount: 874,
		date: new Date(),
		receipt: false,
		email: "Silas22@gmail.com",
		groupOn: "Pending",
		name: "Silas Green",
		transactionLocation: "Austin, TX",
		transactionIssuer: "Emma Watson",
	},
	{
		id: "bhqecj4p",
		amount: 721,
		date: new Date(),
		receipt: false,
		email: "carmella@hotmail.com",
		groupOn: "Pending",
		name: "Carmella White",
		transactionLocation: "Los Angeles, CA",
		transactionIssuer: "David Chen",
	},
	{
		id: "9k3xvs2q",
		amount: 563,
		date: new Date(),
		receipt: true,
		email: "lucas78@gmail.com",
		groupOn: "Tuesday, 10/07/2023",
		name: "Lucas Brown",
		transactionLocation: "Chicago, IL",
		transactionIssuer: "Olivia Martinez",
	},
	{
		id: "7h2ftu8l",
		amount: 429,
		date: new Date(),
		receipt: false,
		email: "emma55@yahoo.com",
		groupOn: "Tuesday, 10/07/2023",
		name: "Emma Davis",
		transactionLocation: "Seattle, WA",
		transactionIssuer: "Daniel Lee",
	},
	{
		id: "1p9xzm3r",
		amount: 692,
		date: new Date(),
		receipt: true,
		email: "noah33@hotmail.com",
		groupOn: "Tuesday, 10/07/2023",
		name: "Noah Wilson",
		transactionLocation: "Denver, CO",
		transactionIssuer: "Sophia Rodriguez",
	},
	{
		id: "4w6ybn0c",
		amount: 518,
		date: new Date(),
		receipt: false,
		email: "sophia12@gmail.com",
		groupOn: "Pending",
		name: "Sophia Taylor",
		transactionLocation: "Boston, MA",
		transactionIssuer: "Ethan Brown",
	},
	{
		id: "2t8jkl5x",
		amount: 935,
		date: new Date(),
		receipt: true,
		email: "oliver89@yahoo.com",
		groupOn: "Wednesday, 10/08/2023",
		name: "Oliver Anderson",
		transactionLocation: "San Francisco, CA",
		transactionIssuer: "Ava Johnson",
	},
	{
		id: "m5gr84i9",
		amount: 316,
		date: new Date(),
		receipt: true,
		email: "ken99@yahoo.com",
		groupOn: "Monday, 10/06/2023",
		name: "Kenneth Johnson",
		transactionLocation: "New York City, NY",
		transactionIssuer: "Sarah Thompson",
	},
	{
		id: "3u1reuv4",
		amount: 242,
		date: new Date(),
		receipt: false,
		email: "Abe45@gmail.com",
		groupOn: "Monday, 10/06/2023",
		name: "Abraham Lincoln",
		transactionLocation: "Springfield, IL",
		transactionIssuer: "Mary Todd",
	},
	{
		id: "derv1ws0",
		amount: 837,
		date: new Date(),
		receipt: true,
		email: "Monserrat44@gmail.com",
		groupOn: "Monday, 10/06/2023",
		name: "Monserrat Rodriguez",
		transactionLocation: "Miami, FL",
		transactionIssuer: "Carlos Sanchez",
	},
	{
		id: "5kma53ae",
		amount: 874,
		date: new Date(),
		receipt: false,
		email: "Silas22@gmail.com",
		groupOn: "Pending",
		name: "Silas Green",
		transactionLocation: "Austin, TX",
		transactionIssuer: "Emma Watson",
	},
	{
		id: "bhqecj4p",
		amount: 721,
		date: new Date(),
		receipt: false,
		email: "carmella@hotmail.com",
		groupOn: "Pending",
		name: "Carmella White",
		transactionLocation: "Los Angeles, CA",
		transactionIssuer: "David Chen",
	},
	{
		id: "9k3xvs2q",
		amount: 563,
		date: new Date(),
		receipt: true,
		email: "lucas78@gmail.com",
		groupOn: "Tuesday, 10/07/2023",
		name: "Lucas Brown",
		transactionLocation: "Chicago, IL",
		transactionIssuer: "Olivia Martinez",
	},
	{
		id: "7h2ftu8l",
		amount: 429,
		date: new Date(),
		receipt: false,
		email: "emma55@yahoo.com",
		groupOn: "Tuesday, 10/07/2023",
		name: "Emma Davis",
		transactionLocation: "Seattle, WA",
		transactionIssuer: "Daniel Lee",
	},
	{
		id: "1p9xzm3r",
		amount: 692,
		date: new Date(),
		receipt: true,
		email: "noah33@hotmail.com",
		groupOn: "Tuesday, 10/07/2023",
		name: "Noah Wilson",
		transactionLocation: "Denver, CO",
		transactionIssuer: "Sophia Rodriguez",
	},
	{
		id: "4w6ybn0c",
		amount: 518,
		date: new Date(),
		receipt: false,
		email: "sophia12@gmail.com",
		groupOn: "Pending",
		name: "Sophia Taylor",
		transactionLocation: "Boston, MA",
		transactionIssuer: "Ethan Brown",
	},
	{
		id: "2t8jkl5x",
		amount: 935,
		date: new Date(),
		receipt: true,
		email: "oliver89@yahoo.com",
		groupOn: "Wednesday, 10/08/2023",
		name: "Oliver Anderson",
		transactionLocation: "San Francisco, CA",
		transactionIssuer: "Ava Johnson",
	},
	{
		id: "m5gr84i9",
		amount: 316,
		date: new Date(),
		receipt: true,
		email: "ken99@yahoo.com",
		groupOn: "Monday, 10/06/2023",
		name: "Kenneth Johnson",
		transactionLocation: "New York City, NY",
		transactionIssuer: "Sarah Thompson",
	},
	{
		id: "3u1reuv4",
		amount: 242,
		date: new Date(),
		receipt: false,
		email: "Abe45@gmail.com",
		groupOn: "Monday, 10/06/2023",
		name: "Abraham Lincoln",
		transactionLocation: "Springfield, IL",
		transactionIssuer: "Mary Todd",
	},
	{
		id: "derv1ws0",
		amount: 837,
		date: new Date(),
		receipt: true,
		email: "Monserrat44@gmail.com",
		groupOn: "Monday, 10/06/2023",
		name: "Monserrat Rodriguez",
		transactionLocation: "Miami, FL",
		transactionIssuer: "Carlos Sanchez",
	},
	{
		id: "5kma53ae",
		amount: 874,
		date: new Date(),
		receipt: false,
		email: "Silas22@gmail.com",
		groupOn: "Pending",
		name: "Silas Green",
		transactionLocation: "Austin, TX",
		transactionIssuer: "Emma Watson",
	},
	{
		id: "bhqecj4p",
		amount: 721,
		date: new Date(),
		receipt: false,
		email: "carmella@hotmail.com",
		groupOn: "Pending",
		name: "Carmella White",
		transactionLocation: "Los Angeles, CA",
		transactionIssuer: "David Chen",
	},
	{
		id: "9k3xvs2q",
		amount: 563,
		date: new Date(),
		receipt: true,
		email: "lucas78@gmail.com",
		groupOn: "Tuesday, 10/07/2023",
		name: "Lucas Brown",
		transactionLocation: "Chicago, IL",
		transactionIssuer: "Olivia Martinez",
	},
	{
		id: "7h2ftu8l",
		amount: 429,
		date: new Date(),
		receipt: false,
		email: "emma55@yahoo.com",
		groupOn: "Tuesday, 10/07/2023",
		name: "Emma Davis",
		transactionLocation: "Seattle, WA",
		transactionIssuer: "Daniel Lee",
	},
	{
		id: "1p9xzm3r",
		amount: 692,
		date: new Date(),
		receipt: true,
		email: "noah33@hotmail.com",
		groupOn: "Tuesday, 10/07/2023",
		name: "Noah Wilson",
		transactionLocation: "Denver, CO",
		transactionIssuer: "Sophia Rodriguez",
	},
	{
		id: "4w6ybn0c",
		amount: 518,
		date: new Date(),
		receipt: false,
		email: "sophia12@gmail.com",
		groupOn: "Pending",
		name: "Sophia Taylor",
		transactionLocation: "Boston, MA",
		transactionIssuer: "Ethan Brown",
	},
	{
		id: "2t8jkl5x",
		amount: 935,
		date: new Date(),
		receipt: true,
		email: "oliver89@yahoo.com",
		groupOn: "Wednesday, 10/08/2023",
		name: "Oliver Anderson",
		transactionLocation: "San Francisco, CA",
		transactionIssuer: "Ava Johnson",
	},
];